apiVersion: v1
kind: Service
metadata:
  name: redis-database-service
spec:
  selector:
    app: redis-database
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-service
spec:
  selector:
    app: auth-service
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 3100
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service-service
spec:
  selector:
    app: chat-service
  type: LoadBalancer
  ports:
  - port: 8082
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: products-service-service
spec:
  selector:
    app: products-service
  ports:
  - port: 8083
    targetPort: 8080
